[package]
name = "connector_agent"
version = "0.1.0"
authors = ["Weiyuan Wu <youngw@sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { path = "./arrow/rust/arrow"}
pyo3 = { version = "0.13.0", features = ["extension-module"] }
rusoto_core = "0.45"
rusoto_s3 = "0.45"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = "0.8"
tokio = { version = "0.2", features = [ "rt-threaded", "io-util", "blocking" ] }
futures = "0.3"
fehler = "1"
failure = "0.1"
flate2 = "1"
strum = { version = "0.20", features = ["derive"] }
postgres = "0.19.0"

[lib]
name = "connector_agent"
crate-type = ["cdylib", "rlib"]

[profile.release] 
debug = true

# [target.x86_64-apple-darwin]
# rustflags = [
#   "-C", "link-arg=-undefined",
#   "-C", "link-arg=dynamic_lookup",
# ]

# [target.aarch64-apple-darwin]
# rustflags = [
#   "-C", "link-arg=-undefined",
#   "-C", "link-arg=dynamic_lookup",
# ]