[package]
authors = ["Weiyuan Wu <youngw@sfu.ca>"]
edition = "2018"
name = "connectorx"
version = "0.2.0-alpha.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow = "4"
bytes = "1"
chrono = "0.4"
csv = "1"
derive_more = "0.99"
dict_derive = "0.3"
env_logger = "0.9"
fallible-streaming-iterator = "0.1"
fehler = "1"
futures = "0.3"
hex = "0.4"
itertools = "0.10"
log = "0.4"
ndarray = "0.15"
num-traits = "0.2"
owning_ref = "0.4"
polars = "0.14"
postgres = {version = "0.19", features = ["with-chrono-0_4", "with-uuid-0_8", "with-serde_json-1"]}
r2d2 = "0.8"
r2d2_mysql = "18.0"
r2d2_postgres = "0.18"
r2d2_sqlite = "0.18"
rand = "0.8"
rayon = "1"
regex = "1"
rusqlite = {version = "0.25", features = ["column_decltype", "chrono", "bundled"]}
rust_decimal = {version = "1", features = ["db-postgres"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sqlparser = "0.9"
thiserror = "1"
url = "2.2"
uuid = "0.8"

[lib]
crate-type = ["cdylib", "rlib"]
name = "connectorx"

[dev-dependencies]
criterion = "0.3"
iai = "0.1"
polars = "0.14"
pprof = {version = "0.5", features = ["flamegraph"]}

[features]
branch = []
default = ["branch"]
fptr = []
