[package]
authors = ["Weiyuan Wu <youngw@sfu.ca>"]
edition = "2018"
name = "connectorx-python"
version = "0.2.0-alpha.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow = "4"
bitfield = "0.13"
bytes = "1"
chrono = "0.4"
connectorx = {path = "../connectorx", default-features = false}
dict_derive = "0.3"
env_logger = "0.9"
fehler = "1"
itertools = "0.10"
libc = "0.2"
log = "0.4"
ndarray = "0.15"
numpy = "0.14"
pyo3 = {version = "0.14", default-features = false, features = ["macros"]}
pyo3-built = "0.4"
rust_decimal = {version = "1", features = ["db-postgres"]}
serde_json = "1"
sqlparser = "0.9"
thiserror = "1"
uuid = "0.8"

[build-dependencies]
built = {version = "0.5", features = ["chrono"]}

[dev-dependencies]
criterion = "0.3"
criterion-macro = "0.3"
iai = "0.1"
pprof = {version = "0.5", features = ["flamegraph", "criterion", "protobuf"]}
rayon = "1"

[lib]
crate-type = ["rlib", "cdylib"]
name = "connectorx_python"

[features]
branch = ["connectorx/branch"]
default = ["extension", "fptr", "nbstr"]
executable = ["pyo3/auto-initialize"]
extension = ["pyo3/extension-module"]
fptr = ["connectorx/fptr"]
nbstr = []
