[tool.poetry]
authors = ["SFU Database System Lab <dsl.cs.sfu@gmail.com>"] 
classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Software Development :: Build Tools",
  "Environment :: Console",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Intended Audience :: Financial and Insurance Industry",
  "Intended Audience :: Healthcare Industry",
  "Topic :: Scientific/Engineering",
  "Framework :: IPython",
] 
description = "" 
include = ["connectorx/*.so", "connectorx/*.pyd"] 
keywords = ["read_sql"] 
license = "MIT" 
maintainers = ["Weiyuan Wu <youngw@sfu.ca>"] 
name = "connectorx" 
readme = "README.md" # Markdown files are supported
version = "0.2.0-alpha.2" 

[tool.poetry.dependencies]
numpy = "^1"
pandas = "^1"
python = "^3.7.1"

[tool.poetry.dev-dependencies]
PyMySQL = "^1.0.2"
SQLAlchemy = "^1.3.23"
black = "^20.8b1"
contexttimer = "^0.3.3"
dask = {extras = ["complete"], version = "^2021.3.0"}
docopt = "^0.6.2"
maturin = "^0.9.4"
modin = "^0.9.0"
psycopg2-binary = "^2.8.6"
pyarrow = "^3.0.0"
pytest = "^6.2"
pytest-benchmark = "^3.4.1"
twine = "^3.4.1"

[tool.pytest.ini_options]
minversion = "6.0"
python_functions = "test_* bench_*"
# python_files = check_*.py
# python_classes = Check
# addopts = "-ra -q"
# testpaths = [
#   "tests",
#   "integration",
# ]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]
