name: import-test

on: 
  workflow_dispatch:
    inputs:
      indexUrl:
        description: 'Index Url'     
        required: true
        default: 'https://test.pypi.org/simple/'
      version:
        description: 'version'  
        required: false
        default: ''


jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Check which python we use
        run: | 
          echo $(which python)

      - name: Install connector agent
        run: |
          pip install pandas numpy

          version='${{ github.event.inputs.version }}'
          if [ -z $version ]
          then
            pip install --index-url ${{ github.event.inputs.indexUrl }} connector-agent
          else
            pip install --index-url ${{ github.event.inputs.indexUrl }} connector-agent==$version
          fi

      - name: Import
        run: python -c "from connector_agent import read_sql"
          